apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ .apps.vllm.namespace }}
labels:
  - includeSelectors: true
    pairs:
      app: vllm
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml