version: '3.8'

services:
  wild-cloud-central-test:
    build: .
    ports:
      - "8081:8081"   # Wild Cloud Central API
      - "8080:80"     # Web interface via nginx
      - "53:53/udp"   # DNS
      - "67:67/udp"   # DHCP  
      - "69:69/udp"   # TFTP
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    stdin_open: true
    tty: true
    restart: "no"