version: '3.8'

services:
  wild-cloud-central:
    build: .
    ports:
      - "8081:8081"   # Web interface
      - "8080:80"     # Nginx HTTP
      - "53:53/udp"   # DNS
      - "67:67/udp"   # DHCP
      - "69:69/udp"   # TFTP
    volumes:
      - ./config.yaml:/etc/wild-cloud-central/config.yaml
      - wild-central-data:/var/lib/wild-cloud-central
      - wild-central-cache:/var/www/html/talos
      - wild-central-tftp:/var/ftpd
    environment:
      - CONFIG_PATH=/etc/wild-cloud-central/config.yaml
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  wild-central-data:
  wild-central-cache:
  wild-central-tftp: