apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: node-feature-discovery
labels:
  - pairs:
      app.kubernetes.io/name: node-feature-discovery
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - namespace.yaml
  - crds.yaml
  - rbac.yaml
  - daemonset.yaml
  - master.yaml