apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui
labels:
  - includeSelectors: true
    pairs:
      app: open-webui
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml