apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: listmonk
  namespace: listmonk
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    external-dns.alpha.kubernetes.io/target: {{ .cloud.domain }}
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - {{ .apps.listmonk.domain }}
      secretName: {{ .apps.listmonk.tlsSecretName }}
  rules:
    - host: {{ .apps.listmonk.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: listmonk
                port:
                  number: 80