apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: listmonk
labels:
  - includeSelectors: true
    pairs:
      app: listmonk
      managedBy: kustomize
      partOf: wild-cloud
resources:
  - namespace.yaml
  - db-init-job.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml