apiVersion: v1
kind: Service
metadata:
  name: listmonk
  namespace: listmonk
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: web